language: generic
sudo: required
dist: focal

before_install:
  - travis_retry sudo apt install opam -y --allow-unauthenticated
  - opam init --compiler=ocaml-base-compiler.4.08.1 --no-setup --yes
  - eval $(opam env)
  - opam install num ocamlfind ocamlbuild --yes
  - cd deps/coq && ./configure -local && make -j2 && cd ../..
  - export PATH=`pwd`/deps/coq/bin:$PATH
  - coqc -v
  - cd deps/itauto && make -j2 && make install && cd ../..

script:
  - TIMED=1 make 2>&1 | tee log.txt | grep -v -e ' ran for ' -e 'Tactic call'
  - python etc/analyze_tactic_comparison.py log.txt
