language: generic
sudo: required
dist: trusty

branches:
  only:
  - master

matrix:
  fast_finish: true
  include:
    - env: COQ_VERSION="master" COQ_PACKAGE="coq"     PPA="ppa:jgross-h/coq-master-daily"
    - env: COQ_VERSION="v8.9"   COQ_PACKAGE="coq"     PPA="ppa:jgross-h/coq-8.10-daily"

before_install:
  - if [ ! -z "$PPA" ]; then sudo add-apt-repository "$PPA" -y; fi
  - sudo apt-get update -q
  - sudo apt-get install $COQ_PACKAGE -y

# script: TIMED=1 TRY_MANGLE_NAMES=1 make -j2 && ./manglenames-stats.sh

script: TIMED=1 make -j2
